[package]
name = "sdl1"
version = "0.1.0"
authors = ["Joel Svensson <svenssonjoel@yahoo.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.3"
rand = "0.7.3"